sudo: false

language: perl
perl:
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.20-shrplib"
  - "5.18"
  - "5.18-shrplib"
  - "5.14"

before_install:
  - cpanm -n Minilla Devel::Cover::Report::Coveralls

script:
  minil build && perl ./Build.PL && ./Build build && cover -test -report coveralls

notifications:
  irc:
    channels:
      - "irc.freenode.org#chupei.pm"
    use_notice: true

